### ISSUE TITLE
bug: signInWithGoogle() won't fire

### ISSUE THREAD

**Issue by kyleabens** [robingenz/capacitor-firebase#39] opened 2022-03-24 05:25 UTC
**Plugin(s):**

"@capacitor-firebase/authentication": "^0.1.1"

**Platform(s):**

iOS

**Current behavior:**

`const res = await FirebaseAuthentication.signInWithGoogle();` does nothing when it's ran and no error is logged either.  
I have added what needs to be added for iOS unless the documentation is missing something.

**Expected behavior:**

when ran, it should pull up Googles authentication window

**Related code:**

```
async googleLogin() {

    try {

        if (this.platform.is('capacitor')) {

            const res = await FirebaseAuthentication.signInWithGoogle();

            const credential = new OAuthProvider('google.com').credential(res.credential);

            await signInWithCredential(this.auth, credential);

          }

    } catch (err) {
        console.log(err);
    }
}
```

**Other information:**

**Capacitor doctor:**

```
Latest Dependencies:

  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/android: 3.4.3
  @capacitor/ios: 3.4.3

Installed Dependencies:

  @capacitor/android: 3.4.3
  @capacitor/cli: 3.4.3
  @capacitor/core: 3.4.3
  @capacitor/ios: 3.4.3

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

**Comment by robingenz** [comment] 2022-03-24 21:30
Seems like a duplicate of https://github.com/robingenz/capacitor-firebase-authentication/discussions/128.

Please check the following:
1. [ ] `npm install @capacitor-firebase/authentication firebase`
2. [ ] `npx cap sync`
3. [ ] Add Firebase to your project if you haven't already: https://firebase.google.com/docs/ios/setup
4. [ ] Verify that this function is included in your app's `AppDelegate.swift`: 
	  ```swift
	  func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
	    return ApplicationDelegateProxy.shared.application(app, open: url, options: options)
	  }
	  ```
5. [ ] Add the `RobingenzCapacitorFirebaseAuthentication/Google` pod to your `Podfile` (usually `ios/App/Podfile`): 
	  ```diff
	  target 'App' do
	  capacitor_pods
	  # Add your Pods here
	  +  pod 'RobingenzCapacitorFirebaseAuthentication/Google', :path => '../../node_modules/@robingenz/capacitor-firebase-authentication'
	  end
	  ```
6. [ ] `npx cap update`
7. [ ] Add custom URL schemes to your Xcode project (see https://github.com/robingenz/capacitor-firebase-authentication/blob/main/docs/setup-google.md#ios)

If this is all met and still doesn't work, then please provide a Minimal, Reproducible Example (see [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)) so i can debug it.

**Comment by lincolnthree** [comment] 2022-04-05 23:22
Same issue here. Have taken all steps as documented but Facebook and Google both do nothing. I just see this in XCode Console.

```
⚡️  To Native ->  FirebaseAuthentication signInWithGoogle 105272611
⚡️  To Native ->  FirebaseAuthentication signInWithFacebook 105272612
```

I am migrating from capacitor-firebase-auth, which was configured and working. Trying to figure out what I have missed, if anything. Will report back if I can find more info.

**Comment by lincolnthree** [comment] 2022-04-05 23:31
Okay, so I have figured one thing out. 

Running `npx cap update` removes the following lines from the Podfile if you put them in the wrong place:

```
  pod 'CapacitorFirebaseAuthentication/Facebook', :path => '../../node_modules/@capacitor-firebase/authentication'
  pod 'CapacitorFirebaseAuthentication/Google', :path => '../../node_modules/@capacitor-firebase/authentication'
```

These must be put in the `target 'App' do` section, as documented, but it's easy to miss that. Fixing this resolved my issue.

**Closed** 2022-05-06 00:17 UTC
Labels: needs: reply, package: authentication
