### ISSUE TITLE
feat: Android background auto authentication signInWithPhoneNumber 

### ISSUE THREAD

**Issue by zawmn** [robingenz/capacitor-firebase#93] opened 2022-05-18 06:23 UTC
**Is your feature request related to a problem? Please describe:**
I'm trying to use signInWithPhoneNumber and then call signInWithCredential to sign-in on the web layer of Firebase JS SDK.

It is working well in iOS.   In Android, it also working if the Phone number trying to login is not in the testing handset. 
If the Phone number is in the testing handset, signInWithCredential got auth/code-expired error. 

I think the problem is with Android Instant verification or Auto-retrieval of SMS code which auto auth in the background before user input SMS code.  So when user input OTP code, it show invalid or expired. 
I can get AuthStateChangeListener with valid user without manual input SMS code. 
In that background auto auth situation, how can I pass the login credential to signInWithCredential to login web layer?

**Describe the solution you'd like:**
Is there any way to disable such background auto authentication?
OR
Is there any event listener where I can get credential to pass signInWithCredential ?

**Describe alternatives you've considered:**

**Additional context:**

**Comment by robingenz** [comment] 2022-05-18 08:12
This looks like a duplicate of #66.

**Closed** 2022-06-18 00:18 UTC
Labels: platform: android, needs: triage, needs: reply, package: authentication
